CREATE TABLE IF NOT EXISTS usuario (
    id_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombres VARCHAR(100) NOT NULL,
    apellidos VARCHAR(100) NOT NULL,
    correo VARCHAR(180) NOT NULL UNIQUE,
    contrasena VARCHAR(255) NOT NULL,
    telefono VARCHAR(30),
    tipo_usuario VARCHAR(20) NOT NULL DEFAULT 'CLIENTE',
    estado VARCHAR(20) NOT NULL DEFAULT 'ACTIVO',
    hora_entrada TIME,
    hora_salida TIME
);

CREATE TABLE IF NOT EXISTS categoria (
    id_categoria BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    descripcion VARCHAR(500),
    estado VARCHAR(20) NOT NULL DEFAULT 'ACTIVA',
    id_usuario_responsable BIGINT,
    CONSTRAINT fk_categoria_empleado
        FOREIGN KEY (id_usuario_responsable)
        REFERENCES usuario(id_usuario)
);

CREATE TABLE IF NOT EXISTS producto (
    id_producto BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(150) NOT NULL,
    descripcion VARCHAR(1000),
    id_categoria BIGINT NOT NULL,
    precio DECIMAL(10, 2) NOT NULL CHECK (precio >= 0),
    stock INT NOT NULL CHECK (stock >= 0),
    estado VARCHAR(20) NOT NULL DEFAULT 'ACTIVO',
    id_usuario_responsable BIGINT,
    CONSTRAINT fk_producto_categoria
        FOREIGN KEY (id_categoria)
        REFERENCES categoria(id_categoria),
    CONSTRAINT fk_producto_empleado
        FOREIGN KEY (id_usuario_responsable)
        REFERENCES usuario(id_usuario)
);

CREATE TABLE IF NOT EXISTS venta (
    id_venta BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario BIGINT NOT NULL,
    fecha_venta TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    subtotal DECIMAL(10, 2) NOT NULL,
    descuento DECIMAL(10, 2) NOT NULL,
    total DECIMAL(10, 2) NOT NULL,
    estado VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
    CONSTRAINT fk_venta_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES usuario(id_usuario)
);

CREATE TABLE IF NOT EXISTS detalle_venta (
    id_detalle BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_venta BIGINT NOT NULL,
    id_producto BIGINT NOT NULL,
    cantidad INT NOT NULL CHECK (cantidad > 0),
    precio_unitario DECIMAL(10, 2) NOT NULL,
    subtotal DECIMAL(10, 2) NOT NULL,
    CONSTRAINT fk_detalle_venta
        FOREIGN KEY (id_venta)
        REFERENCES venta(id_venta),
    CONSTRAINT fk_detalle_producto
        FOREIGN KEY (id_producto)
        REFERENCES producto(id_producto)
);

CREATE TABLE IF NOT EXISTS pago (
    id_pago BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_venta BIGINT NOT NULL,
    fecha_pago TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    monto DECIMAL(10, 2) NOT NULL,
    metodo_pago VARCHAR(30) NOT NULL,
    estado VARCHAR(20) NOT NULL,
    CONSTRAINT fk_pago_venta
        FOREIGN KEY (id_venta)
        REFERENCES venta(id_venta)
);

CREATE TABLE IF NOT EXISTS asistencia (
    id_asistencia BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario BIGINT NOT NULL,
    fecha DATE NOT NULL,
    hora_entrada TIME,
    hora_salida TIME,
    estado VARCHAR(30) NOT NULL,
    CONSTRAINT fk_asistencia_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES usuario(id_usuario)
);
